services:
  - type: web
    name: frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    staticPublishPath: ./dist/frontend/browser 